// <auto-generated />
using System;
using InkFlow.Modules.Billing.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InkFlow.Modules.Billing.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    partial class BillingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("billing")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InkFlow.Modules.Billing.Infrastructure.Persistence.EntitlementAssignmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("PlanVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlanCode", "PlanVersion");

                    b.HasIndex("UserId", "CreatedAt", "Id");

                    b.ToTable("entitlement_assignments", "billing");
                });

            modelBuilder.Entity("InkFlow.Modules.Billing.Infrastructure.Persistence.PlanEntity", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<string>("EntitlementsJson")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<long>("MonthlyQuotaUnits")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("QuotaAlgorithmVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Code", "Version");

                    b.ToTable("plans", "billing");

                    b.HasData(
                        new
                        {
                            Code = "free",
                            Version = 1,
                            EntitlementsJson = "[\"developer.catalog.read\"]",
                            MonthlyQuotaUnits = 1000L,
                            Name = "Free",
                            QuotaAlgorithmVersion = "quota-v1"
                        },
                        new
                        {
                            Code = "pro",
                            Version = 1,
                            EntitlementsJson = "[\"developer.catalog.read\"]",
                            MonthlyQuotaUnits = 100000L,
                            Name = "Pro",
                            QuotaAlgorithmVersion = "quota-v1"
                        },
                        new
                        {
                            Code = "developer",
                            Version = 1,
                            EntitlementsJson = "[\"developer.catalog.read\"]",
                            MonthlyQuotaUnits = 1000000L,
                            Name = "Developer",
                            QuotaAlgorithmVersion = "quota-v1"
                        });
                });

            modelBuilder.Entity("InkFlow.Modules.Billing.Infrastructure.Persistence.UsageLedgerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ApiKeyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("PeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("Units")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "ApiKeyId", "PeriodStart");

                    b.HasIndex("UserId", "PeriodStart", "OccurredAt");

                    b.ToTable("usage_ledger", "billing");
                });

            modelBuilder.Entity("InkFlow.Modules.Billing.Infrastructure.Persistence.UsagePeriodEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("PeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UsedUnits")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "PeriodStart");

                    b.ToTable("usage_periods", "billing");
                });

            modelBuilder.Entity("InkFlow.Modules.Billing.Infrastructure.Persistence.EntitlementAssignmentEntity", b =>
                {
                    b.HasOne("InkFlow.Modules.Billing.Infrastructure.Persistence.PlanEntity", null)
                        .WithMany()
                        .HasForeignKey("PlanCode", "PlanVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
