<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\InkFlow.Application\InkFlow.Application.csproj" />
    <ProjectReference Include="..\InkFlow.Infrastructure\InkFlow.Infrastructure.csproj" />
  </ItemGroup>
</Project>
