<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../InkFlow.BuildingBlocks.Domain/InkFlow.BuildingBlocks.Domain.csproj" />
    <ProjectReference Include="../InkFlow.BuildingBlocks.Application/InkFlow.BuildingBlocks.Application.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>
</Project>