// <auto-generated />
using System;
using InkFlow.Modules.Reading.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InkFlow.Modules.Reading.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ReadingDbContext))]
    partial class ReadingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reading")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InkFlow.Modules.Reading.Infrastructure.Persistence.BookshelfEntryEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CanonicalBookId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "CanonicalBookId");

                    b.HasIndex("UserId", "UpdatedAt");

                    b.ToTable("shelf_entries", "reading");
                });

            modelBuilder.Entity("InkFlow.Modules.Reading.Infrastructure.Persistence.ReaderPreferenceEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("FontSizePercent")
                        .HasColumnType("integer");

                    b.Property<int>("LineHeightPercent")
                        .HasColumnType("integer");

                    b.Property<int>("Theme")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("preferences", "reading");
                });

            modelBuilder.Entity("InkFlow.Modules.Reading.Infrastructure.Persistence.ReadingHistoryEntryEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CanonicalBookId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CanonicalChapterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FirstReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "CanonicalBookId", "CanonicalChapterId");

                    b.HasIndex("UserId", "LastReadAt");

                    b.ToTable("history", "reading");
                });

            modelBuilder.Entity("InkFlow.Modules.Reading.Infrastructure.Persistence.ReadingProgressEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CanonicalBookId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CanonicalChapterId")
                        .HasColumnType("uuid");

                    b.Property<int>("ParagraphIndex")
                        .HasColumnType("integer");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "CanonicalBookId");

                    b.HasIndex("UserId", "UpdatedAt");

                    b.ToTable("progress", "reading");
                });
#pragma warning restore 612, 618
        }
    }
}
